all:
  children:
    pbs_servers:
      hosts:
        vm-pbs:
          ansible_host: 192.168.100.221
    
    backup_clients:
      hosts:
        vm-webserv:
          ansible_host: 192.168.100.222
          backup_role: web
        vm-dbserv:
          ansible_host: 192.168.100.223
          backup_role: database
        vm-fileserv:
          ansible_host: 192.168.100.224
          backup_role: fileserver
    
    pve_cluster:
      hosts:
        hydra-01:
          ansible_host: 192.168.100.241
      vars:
        ansible_user: root
        ansible_become: no
  
  vars:
    ansible_user: debian
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: true
    ansible_become_method: sudo
